//USER

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT= 'USER_LOGOUT';

export const USER_REGISTER_SUCCESS= 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE= 'USER_REGISTER_FAILURE';

//shop 
export const SET_SHOP_CATEGORIES = 'SET_SHOP_CATEGORIES';
export const SET_SHOP_PRODUCTS = 'SET_SHOP_PRODUCTS';
